TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += group3hallprobe.db
DATA += group3hallprobe.proto

#=======================================
include $(TOP)/configure/RULES
